--预算类别主表
insert into T_PM_BUDGET_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, BUDGET_CATEGORY)
values ('20', '20', '装备项目', null);

insert into T_PM_BUDGET_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, BUDGET_CATEGORY)
values ('09', '09', '科研发展基金', null);

insert into T_PM_BUDGET_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, BUDGET_CATEGORY)
values ('19', '19', '科研项目', null);

insert into T_PM_BUDGET_CATEGORY (ID, CATEGORY_CODE, CATEGORY_NAME, BUDGET_CATEGORY)
values ('07', '07', '大学科研健康基金', null);

--预算类别附属表
insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-1001', '19', '1001', '学校管理费', '0', null, '19-10', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-10', '19', '10', '间接费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-09', '19', '09', '其他支出', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-08', '19', '08', '专家咨询费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-07', '19', '07', '劳务费', '1', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-06', '19', '06', '出版/文献/信息传播/知识产权事务费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-05', '19', '05', '会议/差旅/国际合作与交流费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-04', '19', '04', '燃料动力费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-03', '19', '03', '外部协作费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-02', '19', '02', '材料费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-13', '19', '13', '校内协作费', '1', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-12', '19', '12', '不可预见费', '1', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-11', '19', '11', '指定分承包费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-1004', '19', '1004', '项目组绩效津贴', '0', null, '19-10', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-1003', '19', '1003', '承研单位管理费', '0', null, '19-10', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-10', '20', '10', '校内协作费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-09', '20', '09', '其他支出', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-08', '20', '08', '专家咨询费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-07', '20', '07', '劳务费', '1', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-06', '20', '06', '出版/文献/信息传播/知识产权事务费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-05', '20', '05', '会议/差旅/国际合作与交流费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-04', '20', '04', '燃料动力费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-03', '20', '03', '外部协作费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-02', '20', '02', '材料费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-01', '20', '01', '设备费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0103', '20', '0103', '仪器设备租用费', '1', null, '20-01', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0102', '20', '0102', '仪器设备改造维护费', '1', null, '20-01', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0101', '20', '0101', '专用仪器设备、样品样机购置费', '1', null, '20-01', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0206', '20', '0206', '陪试品', '1', null, '20-02', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0205', '20', '0205', '半成品', '1', null, '20-02', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0204', '20', '0204', '成品（含嵌入软件）', '1', null, '20-02', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0203', '20', '0203', '元器件', '1', null, '20-02', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0202', '20', '0202', '辅助材料', '1', null, '20-02', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0201', '20', '0201', '原材料', '1', null, '20-02', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0306', '20', '0306', '软件开发', '1', null, '20-03', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0305', '20', '0305', '技术服务', '1', null, '20-03', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0304', '20', '0304', '试验', '1', null, '20-03', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0303', '20', '0303', '加工、生成', '1', null, '20-03', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0302', '20', '0302', '研制、试制', '1', null, '20-03', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0301', '20', '0301', '设计、研究', '1', null, '20-03', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0402', '20', '0402', '水电费', '0', null, '20-04', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0401', '20', '0401', '燃料费', '0', null, '20-04', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0504', '20', '0504', '外国专家工作费', '0', null, '20-05', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0503', '20', '0503', '市内交通费', '0', null, '20-05', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0502', '20', '0502', '差旅费', '0', null, '20-05', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0501', '20', '0501', '会议费', '1', null, '20-05', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0608', '20', '0608', '专业通信费', '0', null, '20-06', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0607', '20', '0607', '专利申请、知识产权费', '0', null, '20-06', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0606', '20', '0606', '专用软件购置费', '1', null, '20-06', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0605', '20', '0605', '数据采集费', '0', null, '20-06', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0604', '20', '0604', '文献检索费', '0', null, '20-06', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0603', '20', '0603', '翻译费', '0', null, '20-06', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0602', '20', '0602', '图书资料费', '0', null, '20-06', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0601', '20', '0601', '出版印刷费/稿费', '1', null, '20-06', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0907', '20', '0907', '劳保用品', '0', null, '20-09', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0906', '20', '0906', '运杂费', '0', null, '20-09', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0905', '20', '0905', '办公用品、耗材', '1', null, '20-09', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0904', '20', '0904', '技术引进费', '1', null, '20-09', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0903', '20', '0903', '科研试验产生的赔偿费', '0', null, '20-09', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0902', '20', '0902', '随产品交付的专用测试仪器购置费', '1', null, '20-09', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('20-0901', '20', '0901', '通信租线费', '0', null, '20-09', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-01', '19', '01', '设备费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-1002', '19', '1002', '责任单位管理费', '0', null, '19-10', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('0-0', '0', '0', '合计', '0', null, '-1', '0');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0103', '19', '0103', '仪器设备租用费', '1', null, '19-01', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0102', '19', '0102', '仪器设备改造维护费', '1', null, '19-01', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0101', '19', '0101', '专用仪器设备、样品样机购置费', '1', null, '19-01', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0206', '19', '0206', '陪试品', '1', null, '19-02', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0205', '19', '0205', '半成品', '1', null, '19-02', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0204', '19', '0204', '成品（含嵌入软件）', '1', null, '19-02', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0203', '19', '0203', '元器件', '1', null, '19-02', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0202', '19', '0202', '辅助材料', '1', null, '19-02', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0201', '19', '0201', '原材料', '1', null, '19-02', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0306', '19', '0306', '软件开发', '1', null, '19-03', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0305', '19', '0305', '技术服务', '1', null, '19-03', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0304', '19', '0304', '试验', '1', null, '19-03', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0303', '19', '0303', '加工、生成', '1', null, '19-03', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0302', '19', '0302', '研制、试制', '1', null, '19-03', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0301', '19', '0301', '设计、研究', '1', null, '19-03', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0402', '19', '0402', '水电费', '0', null, '19-04', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0401', '19', '0401', '燃料费', '0', null, '19-04', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0504', '19', '0504', '外国专家工作费', '0', null, '19-05', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0503', '19', '0503', '市内交通费', '0', null, '19-05', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0502', '19', '0502', '差旅费', '0', null, '19-05', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0501', '19', '0501', '会议费', '1', null, '19-05', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0608', '19', '0608', '专业通信费', '0', null, '19-06', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0607', '19', '0607', '专利申请、知识产权费', '0', null, '19-06', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0606', '19', '0606', '专用软件购置费', '1', null, '19-06', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0605', '19', '0605', '数据采集费', '0', null, '19-06', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0604', '19', '0604', '文献检索费', '0', null, '19-06', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0603', '19', '0603', '翻译费', '0', null, '19-06', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0602', '19', '0602', '图书资料费', '0', null, '19-06', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0601', '19', '0601', '出版印刷费/稿费', '1', null, '19-06', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0907', '19', '0907', '课题审计费', '0', null, '19-09', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0906', '19', '0906', '运杂费', '0', null, '19-09', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0905', '19', '0905', '办公用品、耗材', '1', null, '19-09', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0904', '19', '0904', '技术引进费', '1', null, '19-09', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0903', '19', '0903', '科研试验产生的赔偿费', '0', null, '19-09', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0902', '19', '0902', '随产品交付的专用测试仪器购置费', '1', null, '19-09', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('19-0901', '19', '0901', '通信租线费', '0', null, '19-09', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('07-02', '07', '02', '医疗费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('07-01', '07', '01', '大病统筹医疗', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0206', '09', '0206', '专家咨询费', '0', null, '09-02', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0205', '09', '0205', '业务接待费', '0', null, '09-02', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0204', '09', '0204', '业务会议费', '1', null, '09-02', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0203', '09', '0203', '车辆维护费', '1', null, '09-02', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0202', '09', '0202', '市内交通费', '0', null, '09-02', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0201', '09', '0201', '差旅费', '0', null, '09-02', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-02', '09', '02', '科研活动费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0106', '09', '0106', '运杂费', '0', null, '09-01', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0105', '09', '0105', '业务通信费', '0', null, '09-01', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0104', '09', '0104', '文献检索/数据采集费', '0', null, '09-01', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0103', '09', '0103', '图书资料费', '0', null, '09-01', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0102', '09', '0102', '出版印刷费', '0', null, '09-01', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0101', '09', '0101', '办公用品/耗材', '1', null, '09-01', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-01', '09', '01', '业务费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-09', '09', '09', '知识产权和法律事务费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-08', '09', '08', '创新成果奖励费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0702', '09', '0702', '自主立项科研条件建设费', '1', null, '09-07', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0701', '09', '0701', '自主立项科学研究费', '1', null, '09-07', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-07', '09', '07', '自主立项科研费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0603', '09', '0603', '科研场所日常维护费', '0', null, '09-06', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0602', '09', '0602', '科研场所配套设备（施）购置/维护费', '1', null, '09-06', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0601', '09', '0601', '科研场所修缮/改造费', '1', null, '09-06', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-06', '09', '06', '场所建设维护费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0502', '09', '0502', '专用仪器设备（软件）维护/定检校验费', '1', null, '09-05', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0501', '09', '0501', '专用仪器设备（软件）购置费', '1', null, '09-05', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-05', '09', '05', '设备购置维护费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0402', '09', '0402', '专家授课费', '0', null, '09-04', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0401', '09', '0401', '人员培训学费', '1', null, '09-04', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-04', '09', '04', '科技人员培养费', '0', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-03', '09', '03', '劳务费', '1', null, '0-0', '1');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0903', '09', '0903', '法律事务费', '0', null, '09-09', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0902', '09', '0902', '知识产权维护费', '0', null, '09-09', '2');

insert into T_PM_BUDGET_CATEGORY_ATTR (ID, CATEGORY_CODE, CATEGORY_CODE_DTL, DETAIL_NAME, DETAIL_SYMBOL, DETAIL_DESC, PID, NODE)
values ('09-0901', '09', '0901', '知识产权申请费', '0', null, '09-09', '2');

