select * 
  from (select r.*,rownum rn
          from (select * from (SELECT '1' as TYPE,
       SEND.ID,
       SEND.SEND_TITLE TITLE,
       SEND.FILE_NUM_PREFIX || '20' || SEND.SEND_YEAR || SEND.SEND_NUM AS FILE_NUM,
       SEND.SEND_TYPE_CODE REG_TYPE,
       SEND.SECRITY_GRADE,
       SEND.UNDERTAKE_UNIT_NAME DUTY_NAME,
       SEND.ARCHIVE_FLAG,
       SEND.CONTACT_ID,
       R.id AS RID,
       SEND.CREATE_DATE
  FROM T_O_SEND_BILL SEND
  JOIN T_O_FLOW_RECEIVE_LOGS R
    ON SEND.ID = R.SEND_RECEIVE_ID
   AND R.OPERATE_STATUS = '0' 
   AND R.RECEIVE_USERID = '${param.userId}'


UNION ALL

SELECT '2' AS TYPE,
       RECEIVE.ID,
       RECEIVE.TITLE,
       RECEIVE.FILE_NUM_PREFIX || '20' || RECEIVE.FILE_NUM_YEAR || RECEIVE.BILL_NUM AS FILE_NUM,
       RECEIVE.REG_TYPE,
       RECEIVE.SECRITY_GRADE,
       RECEIVE.DUTY_NAME,
       RECEIVE.ARCHIVE_FLAG,
       RECEIVE.CONTACT_ID,
       R.id AS RID,
       RECEIVE.CREATE_DATE
  FROM T_O_RECEIVE_BILL RECEIVE
  JOIN T_O_FLOW_RECEIVE_LOGS R
    ON RECEIVE.ID = R.SEND_RECEIVE_ID
   AND R.OPERATE_STATUS = '0'
   AND R.RECEIVE_USERID = '${param.userId}'

   
   UNION ALL
   
   SELECT '3' AS TYPE,
       APPROVAL.ID,
       APPROVAL.TITLE,
       APPROVAL.FILE_NUM_PREFIX || '20' || APPROVAL.APPROVAL_YEAR ||
       APPROVAL.APPLICATION_FILENO AS FILE_NUM,
       REG.REG_TYPE REG_TYPE,
       APPROVAL.SECRITY_GRADE,
       APPROVAL.UNDERTAKE_UNIT_NAME DUTY_NAME,
       APPROVAL.ARCHIVE_FLAG,
       APPROVAL.CONTACT_ID,
       R.id AS RID,
       APPROVAL.CREATE_DATE
  FROM T_O_APPROVAL APPROVAL
  JOIN T_O_SEND_RECEIVE_REG REG
  ON APPROVAL.REG_ID=REG.ID
  JOIN T_O_FLOW_RECEIVE_LOGS R
    ON APPROVAL.ID = R.SEND_RECEIVE_ID
   AND R.OPERATE_STATUS = '0'
   AND R.RECEIVE_USERID = '${param.userId}'


 ORDER BY TYPE ASC,CREATE_DATE DESC
)tb 
 )r where rownum<= ${end})n
 where n.rn >=${start}